[DEBUG]22.04 and 12

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -16,7 +16,7 @@ jobs:
     # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
     # You can convert this to a matrix build if you need cross-platform coverage.
     # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
 
     steps:
     - uses: actions/checkout@v3
@@ -24,17 +24,17 @@ jobs:
     - name: Install LLVM and Clang
       uses: egor-tensin/setup-clang@v1
       with:
-        version: 14
+        version: 12
         platform: x64
 
-    - name: Install LLVM tools (including llvm-symbolizer)
-      run: |
-        sudo apt-get update && sudo apt-get install -y llvm-14
-        which llvm-symbolizer || echo "llvm-symbolizer not found"
-        which clang-14 || echo "clang-14 not found"
+    # - name: Install LLVM tools (including llvm-symbolizer)
+    #   run: |
+    #     sudo apt-get update && sudo apt-get install -y llvm-14
+    #     which llvm-symbolizer || echo "llvm-symbolizer not found"
+    #     which clang-14 || echo "clang-14 not found"
   
-    - name: Export llvm-symbolizer path
-      run: echo "LLVM_SYMBOLIZER_PATH=/usr/lib/llvm-14/bin/llvm-symbolizer" >> $GITHUB_ENV
+    # - name: Export llvm-symbolizer path
+    #   run: echo "LLVM_SYMBOLIZER_PATH=/usr/lib/llvm-14/bin/llvm-symbolizer" >> $GITHUB_ENV
 
     - name: Configure CMake
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
