Update cmake.yml

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -28,7 +28,9 @@ jobs:
         platform: x64
 
     - name: Install LLVM tools (including llvm-symbolizer)
-      run: sudo apt-get update && sudo apt-get install -y llvm-12
+      run: |
+        sudo apt-get update && sudo apt-get install -y llvm-12
+        which llvm-symbolizer || echo "llvm-symbolizer not found"
   
     - name: Export llvm-symbolizer path
       run: echo "LLVM_SYMBOLIZER_PATH=/usr/lib/llvm-12/bin/llvm-symbolizer" >> $GITHUB_ENV
